#!/bin/sh

device_type=$1

raw_volume_info=$(wpctl get-volume @DEFAULT_AUDIO_$device_type@)
volume=$(echo $raw_volume_info | awk '{ print $2 * 100}')
is_muted=$(grep -q 'MUTED' <<< $raw_volume_info && echo "true" || echo "false")

updated_audio=$(
    eww get audio | \
    jq ".${device_type} |= (. + (.volume = $volume | .isMuted = $is_muted))"
)
eww update audio="$(echo -E $updated_audio)"
