#!/bin/sh

handle() {
  case $1 in
    workspacev2*) echo $line | grep 'workspacev2>' | cut -d'>' -f3 | cut -d',' -f2 ;;
  esac
}

hyprctl activeworkspace -j | jq '.id' 
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
