#!/bin/sh

scripts_directory=~/.scripts/wallpaper/
wallpaper_directory=~/pictures/wallpapers

available_wallpapers=$(ls -p "$wallpaper_directory" | grep -v /)
selected_wallpaper=$(echo "$available_wallpapers" | ~/.scripts/shared/dmenu "Wallpapers" "#7199ee")

$scripts_directory/change-wallpaper "${wallpaper_directory}/${selected_wallpaper}"
